<template>
  <a href="#main-content" class="skip-link" @click.prevent="skipToContent">Skip to content</a>

  <ReadingProgressBar :progress="readingProgress" :visible="ebookStore.showProgress" />

  <div v-if="uiStore.sidebarOpen" @click="uiStore.closeSidebar" class="fixed inset-0 bg-black/50 z-40 lg:hidden"></div>

  <AppSidebar v-show="!ebookStore.focusMode || uiStore.sidebarOpen" />

  <div :class="['focus-mode-topbar', { 'focus-mode-topbar--hidden': ebookStore.focusMode && !uiStore.sidebarOpen }]">
    <TopBar
      :title="documentStore.title"
      :sidebar-open="uiStore.sidebarOpen"
      @toggle-toc="ebookStore.toggleToc"
      @toggle-settings="ebookStore.toggleSettings"
    />
  </div>

  <main ref="mainContent" id="main-content" role="main" :class="[
    'h-screen overflow-y-auto transition-all duration-200',
    !ebookStore.focusMode ? 'pt-14' : 'pt-0',
    uiStore.sidebarOpen ? 'lg:pl-[280px]' : '',
  ]" @scroll="onScroll">
    <div class="px-6 py-10 lg:px-8 lg:py-12 mx-auto transition-[max-width] duration-300 ease-out" :style="contentStyle">
      <div v-if="documentStore.loadError" class="error-state">
        <svg class="error-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        <h2>Failed to load document</h2>
        <p class="error-detail">{{ documentStore.loadError }}</p>
        <button @click="retryLoad" class="error-retry">Retry</button>
      </div>

      <div v-else-if="!documentStore.mirrorDocument" class="loading-state">
        <div class="loading-skeleton">
          <div class="skeleton-title"></div>
          <div class="skeleton-line w-3/4"></div>
          <div class="skeleton-line w-full"></div>
          <div class="skeleton-line w-5/6"></div>
        </div>
      </div>

      <template v-else>
        <div v-if="documentStore.mirrorDocument" class="mn-content" :class="{ 'mn-content--reveal': contentRevealed }">
          <MirrorRenderer :blocks="documentStore.mirrorDocument.content || []" :top="true" />
        </div>

        <footer class="doc-fin">
          <div class="doc-fin-rule"></div>
          <h3 class="doc-fin-title">End of document</h3>
          <button @click="scrollToTop" class="doc-fin-btn">Back to top</button>
          <p class="doc-fin-credit">Generated by <a href="https://github.com/metanorma" class="doc-fin-credit-link">Metanorma</a></p>
        </footer>
      </template>
    </div>
  </main>

  <Transition name="back-to-top-fade">
    <button v-if="showBackToTop" class="back-to-top" @click="scrollToTop" title="Back to top">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7"/>
      </svg>
    </button>
  </Transition>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, computed, ref, watch, nextTick } from 'vue'
import { useDocumentStore } from '@/stores/documentStore'
import { useUiStore } from '@/stores/uiStore'
import { useEbookStore } from '@/stores/ebookStore'
import AppSidebar from '@/components/AppSidebar.vue'
import MirrorRenderer from '@/components/MirrorRenderer.vue'
import TopBar from '@/components/TopBar.vue'
import ReadingProgressBar from '@/components/ReadingProgressBar.vue'

const documentStore = useDocumentStore()
const uiStore = useUiStore()
const ebookStore = useEbookStore()
const mainContent = ref<HTMLElement | null>(null)

const contentRevealed = ref(false)
const readingProgress = ref(0)
const showBackToTop = ref(false)

const contentStyle = computed(() => {
  const vars = ebookStore.getCssVariables()
  return { maxWidth: vars['--ebook-max-width'], margin: '0 auto' }
})

watch(() => documentStore.mirrorDocument, (doc) => {
  if (doc) {
    nextTick(() => { contentRevealed.value = true })
  }
}, { immediate: true })

function onScroll() {
  if (!mainContent.value) return
  const el = mainContent.value
  const progress = el.scrollTop / (el.scrollHeight - el.clientHeight) * 100
  readingProgress.value = Math.min(100, Math.max(0, progress))
  showBackToTop.value = el.scrollTop > 400

  const sections = el.querySelectorAll('[id]')
  for (let i = sections.length - 1; i >= 0; i--) {
    const section = sections[i] as HTMLElement
    if (section.getBoundingClientRect().top <= 120) {
      uiStore.setActiveSection(section.id)
      break
    }
  }
}

function scrollToTop() {
  mainContent.value?.scrollTo({ top: 0, behavior: 'smooth' })
}

function skipToContent() {
  mainContent.value?.focus()
  mainContent.value?.scrollTo({ top: 0 })
}

function retryLoad() {
  documentStore.loadFromWindow()
}

onMounted(() => {
  document.addEventListener('keydown', handleKeydown)
  if (window.innerWidth >= 1024) uiStore.openSidebar()
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeydown)
})

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    ebookStore.closeAll()
  } else if (e.key === 'f' && !e.ctrlKey && !e.metaKey) {
    const tag = (e.target as HTMLElement).tagName
    if (tag !== 'INPUT' && tag !== 'TEXTAREA') {
      ebookStore.toggleFocusMode()
    }
  }
}
</script>

<style scoped>
.skip-link { position: absolute; top: -100px; left: 0; background: var(--chrome-accent, #0d9488); color: #fff; padding: 8px 16px; z-index: 100; font-size: 0.85rem; font-weight: 600; border-radius: 0 0 8px 0; text-decoration: none; transition: top 0.1s; }
.skip-link:focus { top: 0; }
:deep(.mn-content--reveal) { animation: content-reveal 0.5s cubic-bezier(0.16, 1, 0.3, 1) both; }
@keyframes content-reveal { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }

.doc-fin { margin-top: 6rem; padding: 3rem 1rem 2rem; display: flex; flex-direction: column; align-items: center; text-align: center; }
.doc-fin-rule { width: 100px; height: 1px; background: linear-gradient(to right, transparent, color-mix(in srgb, var(--ebook-accent) 40%, var(--ebook-border)), transparent); margin-bottom: 2rem; }
.doc-fin-title { font-family: ui-monospace, monospace; font-size: 0.7rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.14em; color: var(--ebook-text-muted); margin: 0 0 1.5rem; }
.doc-fin-btn { padding: 9px 20px; font-size: 0.78rem; font-weight: 500; border-radius: 8px; border: 1px solid var(--ebook-border); color: var(--ebook-text); background: transparent; cursor: pointer; }
.doc-fin-btn:hover { background: var(--ebook-bg-secondary); }
.doc-fin-credit { font-size: 0.6rem; color: var(--ebook-text-muted); opacity: 0.4; margin: 1rem 0 0; }
.doc-fin-credit-link { color: var(--ebook-text-muted); text-decoration: none; }
.doc-fin-credit-link:hover { text-decoration: underline; }

.error-state { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 50vh; gap: 0.75rem; text-align: center; }
.error-icon { width: 40px; height: 40px; color: #f59e0b; }
.error-state h2 { font-size: 1.1rem; font-weight: 600; color: var(--chrome-text); }
.error-detail { font-size: 0.85rem; color: var(--chrome-text-dim); max-width: 300px; }
.error-retry { margin-top: 0.5rem; padding: 8px 20px; font-size: 0.8rem; font-weight: 600; border-radius: 8px; background: var(--chrome-accent, #0d9488); color: #fff; cursor: pointer; }
.error-retry:hover { opacity: 0.9; }

.loading-skeleton { max-width: 500px; margin: 0 auto; padding-top: 2rem; }
.skeleton-title { height: 32px; width: 60%; border-radius: 6px; background: var(--chrome-bg-hover); margin-bottom: 1.5rem; animation: skeleton-pulse 1.5s ease-in-out infinite; }
.skeleton-line { height: 14px; border-radius: 4px; background: var(--chrome-bg-hover); margin-bottom: 0.6rem; animation: skeleton-pulse 1.5s ease-in-out infinite; }
@keyframes skeleton-pulse { 0%, 100% { opacity: 0.4; } 50% { opacity: 1; } }

.focus-mode-topbar { transition: opacity 0.2s ease; }
.focus-mode-topbar--hidden { opacity: 0; pointer-events: none; }

.back-to-top { position: fixed; bottom: 24px; right: 24px; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; background: var(--chrome-bg-glass); color: var(--chrome-text); border: 1px solid var(--chrome-border); backdrop-filter: blur(8px); box-shadow: 0 2px 8px rgba(0, 0, 0, 0.12); cursor: pointer; z-index: 35; transition: background 0.15s ease, transform 0.15s ease; }
.back-to-top:hover { background: var(--chrome-bg-hover); transform: translateY(-2px); }
.back-to-top-fade-enter-active, .back-to-top-fade-leave-active { transition: opacity 0.2s ease, transform 0.2s ease; }
.back-to-top-fade-enter-from, .back-to-top-fade-leave-to { opacity: 0; transform: translateY(16px); }
</style>
