# frozen_string_literal: true

require "basic_document/referenceelements/reference_to_citation_element"

module Metanorma; module Document; module StandardDocument
  # Cross-reference to an bibliographic reference within a _StandardDocument_.
  class StandocReferenceToCitationElement < BasicDocument::ReferenceToCitationElement
    register_element do
      # Casing of the autogenerated label of the cross-reference (typically the name of the class of element
      # referenced).
      nodes :case, XrefCaseType

      # Do not include the autogenerated label of the cross-reference in rendering.
      nodes :droploc, TrueClass
    end
  end
end; end; end
