# frozen_string_literal: true

module Metanorma; module Document; module StandardDocument
  # Casing of the autogenerated label of a cross-reference.
  class XrefCaseType < Core::Node::Enum
  end
end; end; end
