# frozen_string_literal: true

module Metanorma; module Document
  # See: https://metanorma.org/
  module Relaton
  end
end; end

require_relative "relaton/address"
require_relative "relaton/affiliation"
require_relative "relaton/bib_item_locality"
require_relative "relaton/bib_item_size"
require_relative "relaton/bib_item_size_type"
require_relative "relaton/bib_item_type"
require_relative "relaton/bibliographic_date"
require_relative "relaton/bibliographic_date_type"
require_relative "relaton/contact_method"
require_relative "relaton/contribution_info"
require_relative "relaton/contributor"
require_relative "relaton/contributor_role"
require_relative "relaton/copyright_association"
require_relative "relaton/date_time"
require_relative "relaton/document_identifier"
require_relative "relaton/document_relation"
require_relative "relaton/document_relation_type"
require_relative "relaton/document_status"
require_relative "relaton/edition"
require_relative "relaton/full_name"
require_relative "relaton/iso4217_code"
require_relative "relaton/iso8601_date"
require_relative "relaton/keyword_type"
require_relative "relaton/locality_stack"
require_relative "relaton/medium_type"
require_relative "relaton/org_identifier"
require_relative "relaton/organization"
require_relative "relaton/person"
require_relative "relaton/person_identifier"
require_relative "relaton/personal_identifier_type"
require_relative "relaton/phone"
require_relative "relaton/place_type"
require_relative "relaton/price_type"
require_relative "relaton/region_type"
require_relative "relaton/relaton_collection"
require_relative "relaton/series_type"
require_relative "relaton/series_type_type"
require_relative "relaton/specific_locality_type"
require_relative "relaton/title_type"
require_relative "relaton/typed_note"
require_relative "relaton/typed_title_string"
require_relative "relaton/typed_uri"
require_relative "relaton/validity_type"
require_relative "relaton/variant_full_name"
require_relative "relaton/variant_org_name"
require_relative "relaton/version_info"
require_relative "relaton/vocab_id_type"
