#!/usr/bin/env ruby
# frozen_string_literal: true

require "metanorma/document"

begin
  Metanorma::Document::CLI.run(ARGV)
rescue Metanorma::Document::CLI::Error => e
  warn "Error: #{e.message}"
  exit 1
end
